### ISSUE TITLE
Broken regex in @include causes *all* scripts failing to load

### ISSUE THREAD

**Issue by fireattack** [violentmonkey/violentmonkey#1196]
### How to reproduce it?
1. Add this script. Notice it is missing right "/" for regex and has a literal "/" at the end.

```js
// ==UserScript==
// @name        New script - example.com
// @namespace   Violentmonkey Scripts
// @include       /^http:\/\/example.com\/
// @grant       none
// @version     1.0
// @author      -
// @description 2/13/2021, 9:21:13 AM
// ==/UserScript==
```
~~2. Have more proper scripts matching example.com~~
~~3. Open http://example.com~~
2. Open any sites with scripts 

### What is the expected result?

Broken script doesn't load, but others load fine.

### What is the actual result?

Not only the broken one doesn't work, it causes all the others fail to load

### Log

```
example.com/:1 Uncaught (in promise) SyntaxError: Invalid regular expression: /^http:\/\/example.com\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at v (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:27143)
    at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:26472
    at Array.some (<anonymous>)
    at h (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:26394)
    at f (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:26513)
    at b (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:26842)
    at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:20237
    at Array.filter (<anonymous>)
    at M (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:20174)
```

### Environment
- Browser: Chrome
- Browser version: Version 88.0.4324.150 (Official Build) (64-bit)
- Violentmonkey version: 2.12.9
- OS: Windows

**Comment by fireattack** [comment]
That was fast, thank you for the hard work.
