### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by violenttamper** [violentmonkey/violentmonkey#1824]
I have a probability of encountering such problems during use. When clicking on the extended console on some pages or start pages, these problems will appear as shown in the figure, resulting in the inability to open the console page.
![屏幕截图 2023-05-18 140558](https://github.com/violentmonkey/violentmonkey/assets/75355896/1b04c052-ef59-4e56-a2b2-81aaba65d8f1)
![屏幕截图 2023-05-18 140708](https://github.com/violentmonkey/violentmonkey/assets/75355896/f59a3c22-be58-4860-a52b-8b2036b57ca6)
![屏幕截图 2023-05-18 140807](https://github.com/violentmonkey/violentmonkey/assets/75355896/56940f60-2e42-43fe-9e03-025ee743d533)
  I want to know why this situation happened?
#### Environment:
- OS: Windows：Windows 10 Version 22H2 (Build 19045.2965)
- Browser: 6.0.2979.18 (Stable channel) （64 位） 
- Violentmonkey Version:Violentmonkey 2.14.0

**Comment by tophf** [comment]
I couldn't reproduce the problem in Vivaldi. Please copy the **text** of the errors and paste here.

**Comment by violenttamper** [comment]
I think this may be an occasional bug, as I have only encountered it twice so far. The last time was about a week ago. At present, it cannot be reproduced.

**Comment by violenttamper** [comment]
TypeError:  Cannot destructure property ' id'
at OpenEditor (chrome-extension:// jinja
at async ds (chrome-extension:// jinjacc

Error:  {}  in OpenEditor ("")
     at ds                (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/options/index.html)

It may not be complete, but it's probably these error messages.

**Comment by tophf** [comment]
I need the complete text.

**Comment by violenttamper** [comment]
Sorry, although I really wanted to copy the complete text, I only had half of it when I copied it at that time.

**Comment by violenttamper** [comment]
Okay, I just had a problem like yesterday when using it, and I took a screenshot. As shown in the figure:
![屏幕截图 2023-05-19 143228](https://github.com/violentmonkey/violentmonkey/assets/75355896/b5f814ce-9cc7-416b-8e81-f04883c890db)


The error message for copying is as follows:
TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is undefined.
    at OpenEditor (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:185603)
    at async ds (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:210364)

**Comment by tophf** [comment]
Thank you. What was the sequence of actions you performed before seeing the error? I want to reproduce it locally myself.

**Comment by violenttamper** [comment]
I appeared while browsing the webpage, which was random, and of course, it could also be related to the agent still running at the time.

**Comment by violenttamper** [comment]
I seem to have added the webpage panel of the Violantmonkey console settings page in the Vivaldi browser's panel, and there will be an error message when updating the script in the webpage panel. As follows:
TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is undefined.
    at OpenEditor (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:185603)
    at async ds (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:210364)

TypeError: Cannot destructure property 'custom' of 'a[$]' as it is undefined.
    at pt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:159207)
    at gt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:159112)
    at GetData (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:209741)
    at ds (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:210370)
    at _ (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/common-ui.js:1:80407)
    at SetPopup (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/popup/index.js:1:17492)

Error: {} in OpenEditor("")
    at ds (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:210512)
![屏幕截图 2023-05-19 211546](https://github.com/violentmonkey/violentmonkey/assets/75355896/c35bba3e-0c32-4d77-9459-20efd8907ee7)

**Comment by tophf** [comment]
Thank you for the screenshot, it helped me replicate the errors and fix them.

**Comment by violenttamper** [comment]
Thank you. It would be great if you could help solve the problem.
