### ISSUE TITLE
Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.[BUG] 

### ISSUE THREAD

**Issue by Gloryandel** [violentmonkey/violentmonkey#2073]
### Sequence of actions: 
1. install Violentmonkey
2. open Manager Page in Tab
3.  

### Problem: 

```js
Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at En (background/index.js:1:132223)
    at _n (background/index.js:1:131942)
    at async Promise.all (index 0)
    at async Bi (background/index.js:1:143391)
    at async Wi (background/index.js:1:143022)
    at async hc (background/index.js:1:187321)
    at async Promise.all (index 0)
    at async pr (options/index.js:1:86474)
```
![image](https://github.com/violentmonkey/violentmonkey/assets/51497852/5c451a07-6dcc-437e-8824-c6023baea54f)
![image](https://github.com/violentmonkey/violentmonkey/assets/51497852/5f26c86b-3266-4097-913a-aeaf5d7bd226)

#### Environment:
- OS: Windows
- Browser: Chrome 123.0.6312.59
- Violentmonkey Version: v2.18.0

**Comment by tophf** [comment]
I can't reproduce it. Does it happen with a specific userscript?
