### ISSUE TITLE
[BUG] Uncaught Promise Error

### ISSUE THREAD

**Issue by JamShady** [violentmonkey/violentmonkey#2142]
### Sequence of actions: 

I have a custom script that acts on a subset of Amazon pages, i.e.
`// @match        https://*.amazon.co.uk/subdir/*`

This works fine, exactly as you'd expect.

However, on the main Amazon pages, (i.e. not in the /subdir/, but on pretty much every other page) I get the error in the dev console.

This does not appear when browsing other websites, so it seems to be targeted specifically to Amazon, and I can only imagine because of my userscript?

There are no other scripts installed or being used.

### Problem: 

injected.js:1 Uncaught (in promise) Error: Attempting to use a disconnected port object
    at rs (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:146760)
    at ls (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:146873)
    at Run (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:184229)
    at Tc (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:190237)
    at Rc (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:190184)
    at d (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:1767)
Error: callstack before invoking sendMessage:
    at Proxy.<anonymous> (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:2232)
    at Ne (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:3326)
    at nt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:4595)
    at Tt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:7055)
    at Pt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:7152)
    at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:14385

### Expected result:  

No errors

#### Environment:
- OS: Windows 11
- Browser: Chrome 126 
- Violentmonkey Version: 2.20.0

**Comment by tophf** [comment]
I can't reproduce the error. Could you provide a complete step-by-step instruction and code?

**Comment by tophf** [comment]
Never mind, I found the bug in our code.
