### ISSUE TITLE
Brave / unknown errors / injected.js:1

### ISSUE THREAD

**Issue by lopaba** [violentmonkey/violentmonkey#2166]
I have recently installed Violentmonkey and on some websites like youtube.com or twitch.tv i get this in my console: 

> ![image](https://github.com/user-attachments/assets/d07c85f1-c583-4186-9506-f33ff9cc3e0e)
> 
```
 injected.js:1 Uncaught (in promise) Error: Attempting to use a disconnected port object
     at rs (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:146760)
     at ls (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:146873)
     at Run (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:184229)
     at Tc (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:190237)
     at Rc (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:190184)
     at d (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/background/index.js:1:1767)
 Error: callstack before invoking sendMessage:
     at Proxy.<anonymous> (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:2232)
     at Ne (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:3326)
     at nt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:4595)
     at Tt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:7055)
     at Pt (chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:7152)
     at chrome-extension://jinjaccalgkegednnccohejagnlnfdag/injected.js:1:14385
 (anonymous) @ injected.js:1
 Ne          @ injected.js:1           
 nt          @ injected.js:1
 Tt          @ injected.js:1
 Pt          @ injected.js:1
 (anonymous) @ injected.js:1
```

has anybody experienced this or knows the reason for this? I am new and if this is normal, please let me know, I am just curious of why this shows up.

**Comment by tophf** [comment]
It's a bug that was fixed in [beta](https://github.com/violentmonkey/violentmonkey/releases). It doesn't affect functionality.
